# Generated by Django 3.1.7 on 2021-03-13 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0002_auto_20210313_0700'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='author_year',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
