# Generated by Django 3.1.7 on 2021-03-13 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0005_auto_20210313_1316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='college',
            name='number_of_reviews',
        ),
    ]
